INSERT INTO USERS (COMPANY, USER_ID, PASSWORD) VALUES ('cafeCoder', 'hwk0911@gmail.com', '123123');
INSERT INTO USERS (COMPANY, USER_ID, PASSWORD) VALUES ('caca', 'hwk94@gamil.com', '123123');
INSERT INTO STOCKS (USER_ID, CLIENT, PRODUCT_NAME, COLOR, SIZE, AMOUNT) VALUES ('hwk0911@gmail.com', '빨주노초파남보', '(초특가!/1+1할인) 박시핏 무지 긴팔면T', '베이지', 'FREE', '16');
INSERT INTO STOCKS (USER_ID, CLIENT, PRODUCT_NAME, COLOR, SIZE, AMOUNT) VALUES ('hwk0911@gmail.com', '공장', '쫀득', '베이지', 'FREE', '222');
INSERT INTO STOCKS (USER_ID, CLIENT, PRODUCT_NAME, COLOR, SIZE, AMOUNT) VALUES ('hwk94@gamil.com', '공장', '쫀득', '베이지', 'FREE', '222');